k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: ec6eede7-453f-5658-a41d-34a9bc58a4d3
    cluster_name: deploy-preview-dev
- manifest_path: /manifests
  cluster_info:
    cluster_id: ec6eede7-453f-5658-a41d-34a9bc58a4d3
    cluster_name: deploy-preview-dev
