k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: ec6eede7-453f-5658-a41d-34a9bc58a4d3
    cluster_name: deploy-preview-dev
deployment_preview:
  ingress_host: deploy-previews.alice.k736.net
  ingress_port: 443
  ingress_tls: true
  ingress_l5host: deploy-previews.alice.k736.net
  workload_name: quote
  workload_kind: deployment
  workload_namespace: default
  workload_port: 8080
