---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
  namespace: gitops-demo
spec:
  hostname: "*"
  prefix: /backend/
  service: quote
---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: gitops-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: quote
