---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-deploy-preview-PR5
  namespace: deploy-previews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-deploy-preview-PR5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote-deploy-preview-PR5
    spec:
      containers:
        - name: backend
          image: alicewasko/quote-previews:5-e1a1a47
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
