---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-deploy-preview-pr15
  namespace: deploy-previews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-deploy-preview-pr15
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote-deploy-preview-pr15
    spec:
      containers:
        - name: backend
          image: docker.io/alicewasko/quote-deploy-preview:15-68bd469
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
