---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-deploy-preview-pr25
  namespace: deploy-previews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-deploy-preview-pr25
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote-deploy-preview-pr25
    spec:
      containers:
        - name: backend
          image: docker.io/alicewasko/quote-deploy-preview:25-dbf04a8
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
        - name: todd
          image: docker.io/aidanhahn/podd:2.5.3
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
          args:
            - --workload-name=quote
            - --workload-namespace=gitops-demo
            - --ingress-tls=true
            - --ingress-port=443
            - --ingress-host=35.193.14.83
          env:
            - name: AMBASSADOR_CLOUD_APIKEY
              value: MDQ0YjhiZTEtYzk5Mi00MjlmLWI5M2EtYWQ3MGNjMGE2NDdkOlJDdm51WGtCUmpYQU8wTW5rdEcwSkZ6dFBzdHRndnpxN3FZdA==
            - name: TELEPRESENCE_VERSION
              value: v2.5.3
            - name: MANAGER_NAMESPACE
              value: ambassador
      serviceAccount: ambassador-deploy-previews
      serviceAccountName: ambassador-deploy-previews
