---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote-deploy-preview
  namespace: argocd
spec:
  destination:
    namespace: deploy-previews
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/deploy-previews/quote
    repoURL: git@github.com:AliceProxy/deploy-preview.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

