---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote-deploy-preview
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: deploy-previews
  project: default
  source:
    repoURL: 'https://github.com/AliceProxy/deploy-preview.git'
    path: manifests/deploy-previews/quote
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
