---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote
  namespace: argocd
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/quote
    repoURL: git@github.com:AliceProxy/deploy-preview.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
