---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitops-demo
  project: default
  source:
    repoURL: 'https://github.com/AliceProxy/deploy-preview.git'
    path: manifests/quote
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
